AWSTemplateFormatVersion: '2010-09-09'
Resources:
  TableCustomFieldsCustomFields:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
      KeySchema:
      - AttributeName: id
        KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      TableName: LambdaName


# AWSTemplateFormatVersion: '2010-09-09'
# Description: 'Cloudformation master template'
# Parameters: 
#   LambdaName:
#     "Type": "String",
#     "Description": "Lambda Name",
#     "ConstraintDescription": "Valid lambda name"
#   LambdaHandler:
#     "Type": "String",
#     "Description": "Valid lambda handler",
#     "ConstraintDescription": "e.g [model].[function]"

